name: Eliza CLI Tests

on:
  pull_request:
    paths:
      - 'packages/cli/**'
      - '.github/workflows/eliza-cli-tests.yml'
  push:
    branches:
      - main
      - v2-develop
    paths:
      - 'packages/cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Using the longer timeout from cli-tests.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun turbo run build --filter=@elizaos/cli...

      - name: Run CLI tests
        run: |
          # Run with explicit error checking
          echo "Starting CLI tests with exit code handling..."
          
          # Find the wrapper script location
          if [ -f "./packages/cli/__test_scripts__/run_cli_tests_wrapper.sh" ]; then
            WRAPPER_SCRIPT="./packages/cli/__test_scripts__/run_cli_tests_wrapper.sh"
          elif [ -f "./run_cli_tests_wrapper.sh" ]; then
            WRAPPER_SCRIPT="./run_cli_tests_wrapper.sh"
          else
            echo "::error::Could not find run_cli_tests_wrapper.sh in expected locations"
            exit 1
          fi
          
          echo "Using wrapper script: $WRAPPER_SCRIPT"
          bash "$WRAPPER_SCRIPT"
          TEST_EXIT_CODE=$?
          echo "CLI tests completed with exit code: $TEST_EXIT_CODE"
          
          # Explicitly check exit code and fail if non-zero
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "::error::CLI tests failed with exit code $TEST_EXIT_CODE"
            exit $TEST_EXIT_CODE
          fi 